#!/bin/sh
start()
{
     # Mettez ici le démarrage de votre programme
	echo "Starting system irobotique script"
	/usr/local/bin/connman-dispatcher -p /etc/connman-dispatcher &
}

stop()
{
     # Mettez ici un kill sur votre programme
	echo "Stopping system irobotique script"
}

restart()
{
    stop;
    sleep 1;
    start;
}

case $1 in
start)
      start;;
stop)
      stop;;
restart)
      restart;;
*)
      start;;

force-stop)
	stop
	killall -q connman-dispatcher || true
	sleep 2
	killall -q -9 connman-dispatcher || true
        ;;
	 *)
        echo "Usage: /etc/init.d/irobotique {start|stop|force-stop|restart}"
        exit 1
        ;;
esac
exit 0

