#!/bin/bash

# Define a timestamp function
timestamp() {
	date +"%T"
}

up() {
	timestamp >> ~/.iRFwd.log
	echo "[Connection succeeded]" >> ~/.iRFwd.log
	ifconfig >> ~/.iRFwd.log
	echo "[Activation of port Forwarding]" >> ~/.iRFwd.log
	sshpass -p "pwd" autossh -M 0 -q -f -N -t -o "StrictHostKeyChecking no" -o "ServerAliveInterval 300" -o "ServerAliveCountMax 3" -R 2000:localhost:22 gabs48@i-robotique.be >> ~/.iRFwd.log
}

down() {
	timestamp >> ~/.iRFwd.log
	echo "[Deconnection succeeded]" >> ~/.iRFwd.log
	ifconfig >> ~/.iRFwd.log
}

state="$1"

case $state in
    up)
        up
        ;;
    down)
        down
        ;;
esac

