cmd_/home/gabs48/irobotique_tools/wifi_driver/os/linux/../../rate_ctrl/alg_ags.o := gcc -Wp,-MD,/home/gabs48/irobotique_tools/wifi_driver/os/linux/../../rate_ctrl/.alg_ags.o.d  -nostdinc -isystem /usr/lib/gcc/arm-linux-gnueabihf/4.8/include -I/usr/src/linux-3.8.13-bone59/arch/arm/include -Iarch/arm/include/generated  -Iinclude -I/usr/src/linux-3.8.13-bone59/arch/arm/include/uapi -Iarch/arm/include/generated/uapi -I/usr/src/linux-3.8.13-bone59/include/uapi -Iinclude/generated/uapi -include /usr/src/linux-3.8.13-bone59/include/linux/kconfig.h -D__KERNEL__ -mlittle-endian -Iarch/arm/mach-omap2/include -Iarch/arm/plat-omap/include -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -fno-delete-null-pointer-checks -Wno-error=pointer-sign -fno-stack-protector -O2 -fno-dwarf2-cfi-asm -mabi=aapcs-linux -mno-thumb-interwork -funwind-tables -mthumb -Wa,-mimplicit-it=always -Wa,-mno-warn-deprecated -D__LINUX_ARM_ARCH__=7 -march=armv7-a -msoft-float -Uarm -Wframe-larger-than=1024 -fno-stack-protector -Wno-unused-but-set-variable -fomit-frame-pointer -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fconserve-stack -DCC_HAVE_ASM_GOTO -DAGGREGATION_SUPPORT -DPIGGYBACK_SUPPORT -DWMM_SUPPORT -DLINUX -Wall -Wstrict-prototypes -Wno-trigraphs -DSYSTEM_LOG_SUPPORT -DRT28xx_MODE=STA -DCHIPSET=7601U -DRESOURCE_PRE_ALLOC -I/home/gabs48/irobotique_tools/wifi_driver/include -DCONFIG_STA_SUPPORT -DSCAN_SUPPORT -DWPA_SUPPLICANT_SUPPORT -DNATIVE_WPA_SUPPLICANT_SUPPORT -DDOT11_N_SUPPORT -DDOT11N_DRAFT3 -DSTATS_COUNT_SUPPORT -DMT7601U -DMT7601 -DRLT_MAC -DRLT_RF -DRTMP_MAC_USB -DRTMP_USB_SUPPORT -DRTMP_TIMER_TASK_SUPPORT -DRX_DMA_SCATTER -DVCORECAL_SUPPORT -DRTMP_EFUSE_SUPPORT -DNEW_MBSSID_MODE -DRTMP_INTERNAL_TX_ALC -DCONFIG_ANDES_SUPPORT -DDPD_CALIBRATION_SUPPORT -DCONFIG_RX_CSO_SUPPORT -DRTMP_FREQ_CALIBRATION_SUPPORT  -DMODULE  -fno-optimize-sibling-calls -D"KBUILD_STR(s)=\#s" -D"KBUILD_BASENAME=KBUILD_STR(alg_ags)"  -D"KBUILD_MODNAME=KBUILD_STR(mt7601Usta)" -c -o /home/gabs48/irobotique_tools/wifi_driver/os/linux/../../rate_ctrl/.tmp_alg_ags.o /home/gabs48/irobotique_tools/wifi_driver/os/linux/../../rate_ctrl/alg_ags.c

source_/home/gabs48/irobotique_tools/wifi_driver/os/linux/../../rate_ctrl/alg_ags.o := /home/gabs48/irobotique_tools/wifi_driver/os/linux/../../rate_ctrl/alg_ags.c

deps_/home/gabs48/irobotique_tools/wifi_driver/os/linux/../../rate_ctrl/alg_ags.o := \
    $(wildcard include/config/sta/support.h) \

/home/gabs48/irobotique_tools/wifi_driver/os/linux/../../rate_ctrl/alg_ags.o: $(deps_/home/gabs48/irobotique_tools/wifi_driver/os/linux/../../rate_ctrl/alg_ags.o)

$(deps_/home/gabs48/irobotique_tools/wifi_driver/os/linux/../../rate_ctrl/alg_ags.o):
